version: '3.4'

services:
  frontend:
    build: 
      dockerfile: ./docker/frontend/Dockerfile
      context: ./

  web:
    image: nginx
    volumes:
    - ./templates:/etc/nginx/templates
    ports:
    - "3000:80"
    environment:
    - NGINX_HOST=167.99.140.255
    - NGINX_PORT=80