version: '3.8'

services:
  frontend:
    build: 
      dockerfile: ./docker/frontend/Dockerfile
      context: ./
    
  api: 
    build:
      dockerfile: ./docker/python-email-sender/Dockerfile
      context: ./

  nginx:
    build: ./docker/nginx/
    ports:
      - "80:80"